"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { ArrowRight, BatteryCharging, Check, ChevronRight, Clock3, ShieldCheck, Sparkles, Star, Wrench } from "lucide-react";
import { faqs, placeholderNotice } from "@/lib/data";
import { DeviceGlyph, LinkButton, PlaceholderTag, Section } from "./ui";

const reveal = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-80px" }, transition: { duration: .5 } };
export function HomePage() { return <>
  <section className="hero"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="container hero-grid"><motion.div className="hero-copy" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}><p className="eyebrow"><span className="pulse-dot"/> Precision electronics care · Prague <PlaceholderTag/></p><h1>Your device.<br/><em>Working like new</em> again.</h1><p>Professional repair for Apple and other premium electronics. Clear pricing, quality parts, and fast turnaround.</p><div className="hero-actions"><LinkButton href="/repair">Start a repair <ArrowRight size={18}/></LinkButton><LinkButton href="/prices" secondary>View repair prices</LinkButton></div><div className="trust-row"><span><Star size={15} fill="currentColor"/>4.9 rating*</span><span>10,000+ devices*</span><span>Up to 12-month warranty*</span></div></motion.div><motion.div className="hero-visual" initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .65, delay: .12 }}><div className="phone-stage"><div className="phone-shell before"><i/><span className="crack crack-a"/><span className="crack crack-b"/></div><div className="phone-shell after"><i/><div className="screen-art"><span>14:30</span><div/><small>Ready.</small></div></div><div className="repair-chip chip-one"><Wrench/><span><b>Screen restored</b><small>Quality checked</small></span><Check/></div><div className="repair-chip chip-two"><BatteryCharging/><span><b>Battery health</b><small>100% performance</small></span></div></div></motion.div></div>
    <div className="container quick-select"><span>Repair your</span>{[["iPhone", "iPhone"], ["Mac", "MacBook"], ["iPad", "iPad"], ["Watch", "Apple Watch"], ["Samsung", "Galaxy Phone"]].map(([label, kind]) => <Link key={label} href={`/repair?brand=${label === "Samsung" ? "samsung" : "apple"}`}><DeviceGlyph kind={kind} compact/>{label}<ChevronRight/></Link>)}<Link href="/repair">Other<ChevronRight/></Link></div>
  </section>
  <Section eyebrow="DESIGNED AROUND YOU" title="Repair, without the uncertainty." copy="Know what to expect before your device reaches the workbench."><motion.div className="feature-grid" {...reveal}>{[[<Sparkles/>, "Careful diagnostics", "A technician checks the complete device, not just the visible issue."], [<Clock3/>, "Fast turnaround", "Many common phone repairs are completed on the same day."], [<ShieldCheck/>, "Warranty included", "Selected repairs include up to 12 months of service warranty."], [<Check/>, "Clear estimates", "See realistic estimates before booking and approve the final quote."]].map(([icon, title, text]) => <article key={String(title)}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</motion.div></Section>
  <Section className="dark-section" eyebrow="HOW IT WORKS" title="Four steps. Zero guesswork."><div className="process-grid">{[["01", "Choose your device", "Find your exact model in seconds."], ["02", "Select the issue", "See repair options, timing and pricing."], ["03", "Book your repair", "Visit, send it in or request pickup."], ["04", "Get back to life", "Track progress and collect when ready."]].map(([n, title, copy], i) => <motion.article key={n} {...reveal} transition={{ duration: .45, delay: i * .07 }}><b>{n}</b><div><h3>{title}</h3><p>{copy}</p></div></motion.article>)}</div><div className="center-cta"><LinkButton href="/repair">Configure your repair <ArrowRight/></LinkButton></div></Section>
  <Section eyebrow="CRAFT, MADE VISIBLE" title="From damaged to dependable." copy="Every repair ends with careful testing and a final quality check."><motion.div className="before-after" {...reveal}><div className="ba-copy"><span className="eyebrow">DISPLAY REPAIR</span><h3>Precision you can see.</h3><p>Careful disassembly, a premium display, clean seals and full calibration.</p><ul><li><Check/>Multi-point function test</li><li><Check/>Display calibration</li><li><Check/>Clean finish</li></ul></div><div className="ba-visual"><div className="ba-phone damaged"><span>Before</span><i/><b className="crack crack-a"/><b className="crack crack-b"/></div><div className="ba-phone fixed"><span>After</span><i/><div><small>Tuesday</small><strong>9:41</strong></div></div></div></motion.div></Section>
  <Section className="testimonial-section" eyebrow="CUSTOMER CARE" title="The standard is simple: treat every device like it matters."><div className="testimonial"><blockquote>“A calm, transparent repair experience — the kind of service you expect from a premium technology brand.”</blockquote><div><span className="avatar">JP</span><p><b>Example testimonial</b><small>Placeholder · not a real customer review</small></p><span className="stars">★★★★★</span></div></div></Section>
  <Section className="business-cta"><div className="business-inner"><div><p className="eyebrow">FOR BUSINESS</p><h2>Your team’s devices, always in motion.</h2><p>Priority fleet repairs, consolidated invoicing, pickup and a clear service-level process for growing teams.</p><LinkButton href="/business">Explore business service <ArrowRight/></LinkButton></div><div className="fleet"><DeviceGlyph kind="laptop"/><DeviceGlyph kind="phone"/><DeviceGlyph kind="tablet"/><span><b>Fleet care</b><small>One point of contact</small></span></div></div></Section>
  <Section eyebrow="QUESTIONS, ANSWERED" title="What customers ask us."><div className="faq-list">{faqs.slice(0, 5).map(([q, a], i) => <details key={q} open={i === 0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><div className="center-cta"><Link href="/faq" className="text-link">View all questions <ArrowRight/></Link></div></Section>
  <section className="final-cta"><div className="container"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Let’s bring it back to perfect.</h2><p>Choose your device and get an estimate in under a minute.</p><LinkButton href="/repair">Start your repair <ArrowRight/></LinkButton><small>{placeholderNotice}</small></div></section>
  </>; }
